### ISSUE TITLE
Support for any kind of `Collection`

### ISSUE THREAD

**Issue by sauron** [glhd/conveyor-belt#1]
Hello,
First of all, thank you very much for taking the time to build this package.

I'm usually building migrations from one DB to another. For example from a Drupal DB to a Laravel implementation, or from WP to Laravel.

When doing it I usually configure a new connection, and pull from it process the data and insert into a Laravel/Twill app.
For that matter I use the new DB connection for pulling the records like:

```php
DB::connection('drupal')
    ->table('node')
    ->orderBy('node.nid');
```
These kind of queries return a collection, a `Illuminate\Support\Collection`
instead of the collection that eloquent returns `Illuminate\Database\Eloquent\Collection`

Would if be possible to make it generic by changing the `processChunk` function in the [src/IteratesQuery.php](https://github.com/glhd/conveyor-belt/blob/main/src/IteratesQuery.php#L9) to accept `Illuminate\Support\Collection`?

```php
#replace
\\    use Illuminate\Database\Eloquent\Collection;
#by
    use Illuminate\Support\Collection;
```

So the [src/Support/ConveyorBelt.php](https://github.com/glhd/conveyor-belt/blob/main/src/Support/ConveyorBelt.php#L131) needs to update the `getChunkHandler` function to:

```php
    protected function getChunkHandler(): Closure
    {
        return function ($items) {
            $this->command->prepareChunk($items->collect());

            foreach ($items as $item) {
                if (false === $this->presentRow($item)) {
                    return false;
                }
            }

            return true;
        };
    }
```

Please let me know what do you think and if it is ok to build a pull request for it.

Best.

**Comment by inxilpro** [comment]
Hey @sauron — I'm actually refactoring everything to be less coupled to the Eloquent use case. We'll have support for CSV files, Excel spreadsheets, JSON APIs, etc. Once that refactor is done, it should make your use-case much easier to figure out. Hopefully that will be this week or next… let's take a look then and see what the best way to approach it is?

**Comment by sauron** [comment]
Thank you for reply!

It makes total sense!! 
I saw the potential of extending it to everything else too. 

Great stuff!!
Eagerly waiting for the updates!

**Comment by inxilpro** [comment]
@sauron with the `0.3.0` release there's now an `IteratesEnumerable` trait that lets you iterate anything that implements the `Enumerable` interface (including `Collection` and `LazyCollection`). The database-specific traits have also been refactored to remove the chunk handler altogether, so your use-case should just work without needing to get into a custom implementation at all.

**Comment by sauron** [comment]
Thank you!
