### ISSUE TITLE
Step continue amount

### ISSUE THREAD

**Issue by dillingham** [glhd/conveyor-belt#3]
Maybe it would be useful if instead of `yes/no` it was "Step(s)" and defaulted to `1` and `0` or `no` exited

Maybe useful to inspect the first few for accuracy and then let `all` continue when satisfied

**Comment by inxilpro** [comment]
Interesting. I typically just step through until I'm satisfied and then hit `n` and run it again outside of step mode. I can see an argument for letting you hop out of step mode and into "regular" mode, though.

What if when you chose "no" it then asked you if you wanted to exit or continue running with step mode disabled?

**Comment by dillingham** [comment]
@inxilpro Ah interesting. I was just imagining that rerunning the entire job might process the same ones. I would imagine no would exit immediately if there was an issue with what you were inspecting

**Comment by inxilpro** [comment]
Yeah, it will definitely start from the beginning again. I just always write my commands so that they can be run multiple times without issue—either by truncating the table in `beforeFirstQuery` or by using `updateOrCreate`. In my experience you often need to re-run these types of commands, so I just prepare for that from the get-go.

**Comment by inxilpro** [comment]
That said, a `--resume` flag might be neat.

**Comment by dillingham** [comment]
@inxilpro True [idempotent jobs](http://joycse06.github.io/blog/2016/09/designing-good-background-jobs-idempotence/) are definitely the way to go.. something I didn't really learn about until this year to be honest.. old me would of stumbled with the rerunning logic. Anyways.. not critiques.. just ideas cause this is a cool package and got the mind a thinkin'

**Comment by inxilpro** [comment]
I'm going to close this, but I may look into a `--resume` flag at some point!
